services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Update datasource URL to point to the MySQL container 'db'
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/novisign?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ******
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ******
      MYSQL_DATABASE: novisign
    ports:
      - "3306:3306"
